apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | default "istio-job" }}
  labels:
    {{- include "jxl-boot.labels" . | nindent 4 }}
  annotations:
{{- with .Values.serviceAccount.annotations }}
  {{- toYaml . | indent 4 }}
{{- end }}
