apiVersion: batch/v1
kind: Job
metadata:
  labels:
    release: jenkins-x
  name: {{ .Values.job.name | default "istio-job" }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  backoffLimit: 5
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        release: jenkins-x
    spec:
      initContainers:
      - args:
        - install
        - --set
        - profile={{ .Values.profile | default "default" }}
        - --set
        - values.global.k8sIngress.enabled=true
        - --set
        - values.gateways.istio-ingressgateway.sds.enabled=true
        command:
        - istioctl
        image: "{{ .Values.image.repository }}:{{ .Chart.Version }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: job1
      containers:
      - args:
        - install
        - -f
        - istio-minimal-operator.yml
        command:
        - istioctl
        image: "{{ .Values.image.repository }}:{{ .Chart.Version }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: job2
      restartPolicy: Never
      serviceAccountName: {{ .Values.serviceAccount.name | default "istio-job" }}
